defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
account: rrg-bengioy-ad
timeout_min: 179 # 3h: 180m; 5h: 300m
tasks_per_node: 1
nodes: 1
name: ${hydra.job.name}
signal_delay_s: 600
max_num_timeout: 20
additional_parameters: {}
setup: 
  - "export HF_HUB_OFFLINE=1"
mem_gb: 8
gres: gpu:h100:1
cpus_per_task: 2
array_parallelism: 24