defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
timeout_min: 30 #3h: 180m #3.5h: 210m
tasks_per_node: 1
nodes: 1
name: ${hydra.job.name}
comment: null
exclude: null
signal_delay_s: 600
max_num_timeout: 20
additional_parameters: {}
setup: []
gres: gpu:a100l:1
mem_gb: 32
cpus_per_task: 6
partition: unkillable
# array_parallelism: 24